### ISSUE TITLE
SIGSEGV when executing a playbook with playbook-action

### ISSUE THREAD

**Issue by antonatos** [COSSAS/SOARCA#258]
How to reproduce:

1. Do a POST /playbook for playbook get_tor_nodes.json (attached, id playbook--cd034204-126c-44a9-9fea-45f7faeab88c)
2. Do a POST /trigger/playbook for playbook playbook_action_test.json (also attached)

The playbook playbook playbook_action_test.json contains a playbook-action step that refers to get_tor_nodes.json : 
"playbook-action--f1aeed6f-6097-44ef-880a-7f1b1e0bd192": {
      "type": "playbook-action",
      "playbook_id": "playbook--cd034204-126c-44a9-9fea-45f7faeab88c",
      "on_completion": "end--a0938425-5ea7-4a48-8ce6-1fb8b8cf6915"
 }

SOARCA crashes with the following stack:

Please check https://pkg.go.dev/github.com/gin-gonic/gin#readme-don-t-trust-all-proxies for details.
[GIN-debug] Listening and serving HTTP on :8080
[GIN-debug] redirecting request 307: /playbook/ --> /playbook/
panic: assignment to entry in nil map

goroutine 142 [running]:
soarca/models/cacao.(*Variables).InsertOrReplace(...)
        /home/santonatos/SOARCA/models/cacao/variables.go:35
soarca/models/cacao.(*Variables).Merge(...)
        /home/santonatos/SOARCA/models/cacao/variables.go:84
soarca/internal/executors/playbook_action.(*PlaybookAction).Execute(_, {{0x20, 0x7a, 0x73, 0x5, 0xa5, 0xb9, 0x11, 0xef, 0x8c, ...}, ...}, ...)
        /home/santonatos/SOARCA/internal/executors/playbook_action/playbook_action.go:63 +0x709
soarca/internal/decomposer.(*Decomposer).ExecuteStep(_, {{0xc001836840, 0xf}, {0xc000fe8cc0, 0x35}, {0x0, 0x0}, {0x0, 0x0}, {0x0, ...}, ...}, ...)
        /home/santonatos/SOARCA/internal/decomposer/decomposer.go:201 +0x8d5
soarca/internal/decomposer.(*Decomposer).ExecuteBranch(0xc00027b688, {0xc000fe8c80, 0x35}, 0xc0012b3b48)
        /home/santonatos/SOARCA/internal/decomposer/decomposer.go:158 +0x389
soarca/internal/decomposer.(*Decomposer).execute(_, {{0xc0010fe690, 0x2e}, {0xc001836808, 0x8}, {0xc001836850, 0x9}, {0xc0002a4c78, 0x14}, {0xc0002c2b00, ...}, ...})
        /home/santonatos/SOARCA/internal/decomposer/decomposer.go:111 +0x371
soarca/internal/decomposer.(*Decomposer).ExecuteAsync(_, {{0xc0010fe690, 0x2e}, {0xc001836808, 0x8}, {0xc001836850, 0x9}, {0xc0002a4c78, 0x14}, {0xc0002c2b00, ...}, ...}, ...)
        /home/santonatos/SOARCA/internal/decomposer/decomposer.go:84 +0x205
created by soarca/routes/trigger.(*TriggerApi).execute in goroutine 146
        /home/santonatos/SOARCA/routes/trigger/trigger_api.go:164 +0x159

**Comment by antonatos** [comment]
[get_tor_nodes.json](https://github.com/user-attachments/files/17804753/get_tor_nodes.json)
[playbook_action_test.json](https://github.com/user-attachments/files/17804754/playbook_action_test.json)
